/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.8
 * Generated at: 2020-09-17 14:26:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("   <head>\r\n");
      out.write("      <meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("      <title>Container System</title>\r\n");
      out.write("      <meta charset=\"utf-8\">\r\n");
      out.write("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Poppins:200,300,400,700,900|Display+Playfair:200,300,400,700\">\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/fonts/icomoon/style.css\">\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/bootstrap.min.css\">\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/magnific-popup.css\">\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/jquery-ui.css\">\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/owl.carousel.min.css\">\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/owl.theme.default.min.css\">\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/bootstrap-datepicker.css\">\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/fonts/flaticon/font/flaticon.css\">\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/aos.css\">\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\">\r\n");
      out.write("      <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/fonts/font-awesome-4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("      <!--===============================================================================================-->\r\n");
      out.write("      <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/fonts/Linearicons-Free-v1.0.0/icon-font.min.css\">\r\n");
      out.write("      <!--===============================================================================================-->\r\n");
      out.write("      <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/vendor/animate/animate.css\">\r\n");
      out.write("      <!--===============================================================================================-->  \r\n");
      out.write("      <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/vendor/css-hamburgers/hamburgers.min.css\">\r\n");
      out.write("      <!--===============================================================================================-->\r\n");
      out.write("      <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/vendor/animsition/css/animsition.min.css\">\r\n");
      out.write("      <!--===============================================================================================-->\r\n");
      out.write("      <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/vendor/select2/select2.min.css\">\r\n");
      out.write("      <!--===============================================================================================-->  \r\n");
      out.write("      <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/vendor/daterangepicker/daterangepicker.css\">\r\n");
      out.write("      <!--===============================================================================================-->\r\n");
      out.write("      <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/util.css\">\r\n");
      out.write("      <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main.css\">\r\n");
      out.write("      \r\n");
      out.write("      <script src=\"https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js\"></script>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("<style>\r\n");
      out.write(".ml9 {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  font-weight: 400;\r\n");
      out.write("  font-size: 2em;\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ml9 .text-wrapper {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  padding-top: 0.2em;\r\n");
      out.write("  padding-right: 0.05em;\r\n");
      out.write("  padding-bottom: 0.1em;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ml9 .letter {\r\n");
      out.write("  transform-origin: 50% 100%;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  line-height: 1em;\r\n");
      out.write("}\r\n");
      out.write("      \t\r\n");
      out.write("      </style>\r\n");
      out.write("      \r\n");
      out.write("   </head>\r\n");
      out.write("   <body>\r\n");
      out.write("      <div class=\"site-wrap\">\r\n");
      out.write("         <div class=\"site-mobile-menu\">\r\n");
      out.write("            <div class=\"site-mobile-menu-header\">\r\n");
      out.write("               <div class=\"site-mobile-menu-close mt-3\">\r\n");
      out.write("                  <span class=\"icon-close2 js-menu-toggle\"></span>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"site-mobile-menu-body\"></div>\r\n");
      out.write("         </div>\r\n");
      out.write("         <header class=\"site-navbar py-3\" role=\"banner\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("               <div class=\"row align-items-center\">\r\n");
      out.write("                  <div class=\"col-11 col-xl-2\">\r\n");
      out.write("                     <h1 class=\"mb-0\"><a href=\"index.html\" class=\"text-white h2 mb-0\">SRAM Container</a></h1>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-12 col-md-10 d-none d-xl-block\">\r\n");
      out.write("                     <nav class=\"site-navigation position-relative text-right\" role=\"navigation\">\r\n");
      out.write("                        <ul class=\"site-menu js-clone-nav mx-auto d-none d-lg-block\">\r\n");
      out.write("                           <li class=\"active\"><a href=\"#\">Home</a></li>\r\n");
      out.write("                           <li class=\"has-children\">\r\n");
      out.write("                              <a href=\"services.html\">Services</a>\r\n");
      out.write("                              <ul class=\"dropdown\">\r\n");
      out.write("                                 <li> \r\n");
      out.write("                                 <li class=\"has-children\">\r\n");
      out.write("                                    <a href=\"storage.html\">Storage</a>\r\n");
      out.write("                                    <ul class=\"dropdown\">\r\n");
      out.write("                                       <li>\r\n");
      out.write("                                          <a href=\"dry.html\">Dry Container</a>\r\n");
      out.write("                                          <a href=\"cold.html\">Cold Container</a>\r\n");
      out.write("                                       </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                 </li>\r\n");
      out.write("                                 </li>\r\n");
      out.write("                                 <li><a href=\"transport.html\">Transport</a></li>\r\n");
      out.write("                                 <li><a href=\"shipping.html\">Shipping</a></li>\r\n");
      out.write("                              </ul>\r\n");
      out.write("                           </li>\r\n");
      out.write("                           <li><a href=\"contact.html\">Contact Us</a></li>\r\n");
      out.write("                           <li><a href=\"about.html\">About Us</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                     </nav>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"d-inline-block d-xl-none ml-md-0 mr-auto py-3\" style=\"position: relative; top: 3px;\"><a href=\"#\" class=\"site-menu-toggle js-menu-toggle text-white\"><span class=\"icon-menu h3\"></span></a></div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      </header>\r\n");
      out.write("      <div class=\"limiter\">\r\n");
      out.write("         <div class=\"container-login100\" style=\"background-image: url('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/hero_bg_1.jpg');\">\r\n");
      out.write("            <div class=\"wrap-login100 p-t-130 p-b-70\">\r\n");
      out.write("               <center><h2 class=\"ml9\">\r\n");
      out.write("\t\t\t\t  <span class=\"text-wrapper\">\r\n");
      out.write("\t\t\t\t    <span class=\"letters\">Account Login</span>\r\n");
      out.write("\t\t\t\t  </span>\r\n");
      out.write("\t\t\t\t</h2></center>\r\n");
      out.write("            \r\n");
      out.write("               <div id=\"booking\" class=\"section\">\r\n");
      out.write("                  <div class=\"section-center\">\r\n");
      out.write("                     <div class=\"container\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                           <div class=\"booking-form\">\r\n");
      out.write("                              <form name=\"login\" method=\"post\" action=\"login\" modelAttribute=\"login\">\r\n");
      out.write("                                 <div class=\"row\">\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                       <span class=\"form-label\">Username</span>\r\n");
      out.write("                                       <input class=\"form-control\" type=\"text\" name=\"username\" placeholder=\" &nbsp; User name\" maxlength=\"90\" size=\"90\" required>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class=\"row\">\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                       <span class=\"form-label\">Password</span>\r\n");
      out.write("                                       <input class=\"form-control\" type=\"password\" name=\"password\" id=\"pw\" maxlength=\"90\" size=\"90\" placeholder=\" &nbsp; Password\" required>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class=\"row\">\r\n");
      out.write("                                 <div class=\"form-group\" style=\"color: white;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"custom-control custom-checkbox\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\">&nbsp;Remember me</input>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("                                 <div class=\"container-login100-form-btn m-t-32\">\r\n");
      out.write("                                    <button class=\"login100-form-btn\" onclick=\"valiateLogin()\">\r\n");
      out.write("                                    Login\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 \r\n");
      out.write("                                 <div class=\"mt-4\" style=\"color: white;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"d-flex justify-content-center links\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tDon't have an account? <a href=\"register.jsp\" class=\"ml-2\">Register here</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"d-flex justify-content-center links\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Forgot your password?</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("                              </form>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <br>\r\n");
      out.write("      <center> \r\n");
      out.write("         </div>\r\n");
      out.write("      </center>\r\n");
      out.write("           \r\n");
      out.write("         <footer class=\"site-footer\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("               <div class=\"row\">\r\n");
      out.write("                  <div class=\"col-md-12\">\r\n");
      out.write("                     <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-3\">\r\n");
      out.write("                           <h2 class=\"footer-heading mb-4\">Quick Links</h2>\r\n");
      out.write("                           <ul class=\"list-unstyled\">\r\n");
      out.write("                              <li><a href=\"#\">Home</a></li>\r\n");
      out.write("                              <li><a href=\"about\">About Us</a></li>\r\n");
      out.write("                              <li><a href=\"contact\">Contact Us</a></li>\r\n");
      out.write("                           </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-3\">\r\n");
      out.write("                           <h2 class=\"footer-heading mb-4\">Services</h2>\r\n");
      out.write("                           <ul class=\"list-unstyled\">\r\n");
      out.write("                              <li><a href=\"dry\">Dry Container</a></li>\r\n");
      out.write("                              <li><a href=\"cold\">Cold Container</a></li>\r\n");
      out.write("                              <li><a href=\"shipping\">Shipping</a></li>\r\n");
      out.write("                              <li><a href=\"transport\">Transport</a></li>\r\n");
      out.write("                           </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-3\">\r\n");
      out.write("                           <h2 class=\"footer-heading mb-4\">Contact</h2>\r\n");
      out.write("                           <!-- Links -->\r\n");
      out.write("                           <p>\r\n");
      out.write("                              <i class=\"fas fa-home\"></i> India\r\n");
      out.write("                           </p>\r\n");
      out.write("                           <p>\r\n");
      out.write("                              <i class=\"far fa-envelope\"></i> info@sram.com\r\n");
      out.write("                           </p>\r\n");
      out.write("                           <p>\r\n");
      out.write("                              <i class=\"fas fa-phone\"></i> + 01 234 567 88\r\n");
      out.write("                           </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- Grid column -->\r\n");
      out.write("                        <div class=\"col-md-3\">\r\n");
      out.write("                           <h2 class=\"footer-heading mb-4\">Follow Us</h2>\r\n");
      out.write("                           <a href=\"#\" class=\"pl-0 pr-3\"><span class=\"icon-facebook\"></span></a>\r\n");
      out.write("                           <a href=\"#\" class=\"pl-3 pr-3\"><span class=\"icon-twitter\"></span></a>\r\n");
      out.write("                           <a href=\"#\" class=\"pl-3 pr-3\"><span class=\"icon-instagram\"></span></a>\r\n");
      out.write("                           <a href=\"#\" class=\"pl-3 pr-3\"><span class=\"icon-linkedin\"></span></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </footer>\r\n");
      out.write("      </div>\r\n");
      out.write("     \r\n");
      out.write("      <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("      <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("      <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-ui.js\"></script>\r\n");
      out.write("      <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/popper.min.js\"></script>\r\n");
      out.write("      <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("      <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("      <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("      <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.countdown.min.js\"></script>\r\n");
      out.write("      <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("      <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/bootstrap-datepicker.min.js\"></script>\r\n");
      out.write("      <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/aos.js\"></script>\r\n");
      out.write("      <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/main.js\"></script>\r\n");
      out.write("      \r\n");
      out.write("      <script>\r\n");
      out.write("  var textWrapper = document.querySelector('.ml9 .letters');\r\n");
      out.write("  textWrapper.innerHTML = textWrapper.textContent.replace(/\\S/g, \"<span class='letter'>$&</span>\");\r\n");
      out.write("\r\n");
      out.write("  anime.timeline({loop: true})\r\n");
      out.write("    .add({\r\n");
      out.write("      targets: '.ml9 .letter',\r\n");
      out.write("      scale: [0, 1],\r\n");
      out.write("      duration: 1500,\r\n");
      out.write("      elasticity: 600,\r\n");
      out.write("      delay: (el, i) => 45 * (i+1)\r\n");
      out.write("    }).add({\r\n");
      out.write("      targets: '.ml9',\r\n");
      out.write("      opacity: 0,\r\n");
      out.write("      duration: 1000,\r\n");
      out.write("      easing: \"easeOutExpo\",\r\n");
      out.write("      delay: 1000\r\n");
      out.write("    });\r\n");
      out.write("  </script>\r\n");
      out.write("   </body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
